### ISSUE TITLE
Get-PowerBI Usage Script

### ISSUE THREAD

**Issue by Tassaditsolotech** [ssugar/Blog#1]
when i execute the command: .\Get-PowerBIUsage.ps1 -startSubscription , using the scrip https://github.com/ssugar/Blog/blob/master/PowerBIUsage/Scripts/Get-PowerBIUsage.ps1

i have this error:
{"error":{"code":"AF10001","message":"The permission set () sent in the request does not include the expected permission."}}
Au caractère C:\Users\tassadit.ouldmahamme\Desktop\UsagePowerBI\Get-PowerBIUsage1.ps1:42 : 17
+ ... $response = Invoke-RestMethod -Uri $uri -ContentType "application/x-w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by ssugar** [comment]
Did you run through the AAD application setup steps in the blog?
https://github.com/ssugar/Blog/blob/master/PowerBIUsage/PowerBIUsageReport.md

**Comment by Tassaditsolotech** [comment]
thank you very much, after following the steps, I succeeded, but I wanted the CreationTime in the form of date not datetime, and I failed to make it cast in the code powerBIUsage.ps1, any help please

**Comment by ssugar** [comment]
You should be able to do something like this between lines 109 and 110:
ForEach ($entry in $Entries) { 
    $entry.CreationTime = (Get-Date -Date $entry.CreationTime -Format "MM/dd/yyyy")
}
This should loop through all the entries and reset the date from datetime to a date

The other way we often handle this is by loading the resulting data into a SQL database and then we can alter things much easier within SQL or when transforming data in Power BI (which is something that can be done from a standard Power BI dataset vs a streaming dataset in Power BI)

**Comment by Tassaditsolotech** [comment]
thnk you [ssugar](https://github.com/ssugar) for your quick answer, i will try your 2 idea, to load the resulting in SQL, 
surely it will take some time for me because I don't know powershell , thanks a lot for your help

**Comment by ssugar** [comment]
As a quick FYI, there is a SQL module for Powershell that you could use to help move data into a SQL server.  Specifically this command allows you to run a SQL query (like an insert statment) from Powershell:
https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps

**Comment by ssugar** [comment]
I also have a colleague working on an updated version of this blog that will retrieve the data using native azure data factory commands (no more powershell) and will write the output to SQL (for easier data transformations).  Probably a month or two before that is ready though.

**Comment by Tassaditsolotech** [comment]
thank you for your quick answer, I consulted the link that  you sent me, but I didn't understand how I can include the SQL command in the code Get-PowerBIUsage.ps1

**Comment by ssugar** [comment]
You'd need to install (install-module sqlserver) and import (import-module sqlserver) the SqlServer module into Powershell.  After that you could run the invoke-sqlcmd command from within Powershell (including within the script).  

You'll probably need to do some research on Powershell to get you to the right answer, probably a bit out of scope for the article I wrote here.

As noted before, one of my colleagues is writing up a new version that won't need Powershell anymore - I've actually seen a first draft of it, so it's probably closer to a few weeks away from being published.

**Comment by Tassaditsolotech** [comment]
Hi, how can I be notified when your colleague releases the new version?thank you

**Comment by nvwingerden** [comment]
Thanks for the fast reply, however when executing .\Get-PowerBIUsage.ps1 -startSubscription the following error appears:

PS C:\Users\PBIadmin> .\Get-PowerBIUsage.ps1 -startSubscription
.\Get-PowerBIUsage.ps1 : The term '.\Get-PowerBIUsage.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ .\Get-PowerBIUsage.ps1 -startSubscription
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Get-PowerBIUsage.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ssugar** [comment]
make sure the .\Get-PowerBIUsage.ps1 file exists within the folder you're executing that command from.

That error indicates that the .\Get-PowerBIUsage.ps1 file doesn't exist within your c:\Users\PBIadmin folder

**Comment by Tassaditsolotech** [comment]
@ssugar please i have 2 questions:
1.how can I be notified when your colleague releases the new version?thank you
2. i trayed this command to connect tosql database : Read-SqlTableData -ServerInstance "d365-byod-prod-01.database.windows.net\BYOD-PROD-01" -DatabaseName "BYOD-PROD-01" -SchemaName "dbo" -TableName "PowerBIUsage"
3. Read-SqlTableData : Échec de la connexion au serveur d365-byod-prod-01.database.windows.net\BYOD-PROD-01.
Au caractère Ligne:1 : 1
+ Read-SqlTableData -ServerInstance "d365-byod-prod-01.database.windows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (d365-byod-prod-...et\BYOD-PROD-01:String) [Read-SqlTableData], ConnectionFailureException
    + FullyQualifiedErrorId : ConnectionToServerFailed,Microsoft.SqlServer.Management.PowerShell.ReadSqlTableData

but the same informations of database works wih  others tools as sql server, talend, powerBi.
I followed  this link:https://docs.microsoft.com/en-us/powershell/module/sqlserver/write-sqltabledata?view=sqlserver-ps
thank you

**Comment by nvwingerden** [comment]
Found the culprit, I needed to ad one time the following line in the Get-PowerBIUsage.ps1 script: 
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
After that I could execute: .\Get-PowerBIUsage.ps1 -startSubscription

**Comment by Tassaditsolotech** [comment]
hi [ssugar], 
is there anything new about the program that your colleague was asked to develop on the sql script that you already told me about.
thank you

**Comment by Tassaditsolotech** [comment]
Thank you a lot

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
