### ISSUE TITLE
Get-PowerBI Usage Script #1 problems 

### ISSUE THREAD

**Issue by Tassaditsolotech** [ssugar/Blog#2]
@ssugar , you said to me last time in old ticket that you also have a colleague working on an updated version of this blog that will retrieve the data using native azure data factory commands (no more powershell) and will write the output to SQL (for easier data transformations). Probably a month or two before that is ready though.
is there any news about this version?
thankyou a lot

**Comment by ssugar** [comment]
Sorry for the slow reply - been a busy summer.  Here's the article by my colleague:
https://www.proserveit.com/blog/power-bi-usage-metrics-across-all-workspaces-using-pbi-graph-api
